# Generated by Django 3.2 on 2023-12-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_remove_comentario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='meGusta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noMeGusta',
            field=models.IntegerField(default=0),
        ),
    ]
