# Generated by Django 3.2 on 2023-12-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_auto_20231208_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='meGusta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='noMeGusta',
            field=models.IntegerField(default=0),
        ),
    ]
